# -*- coding: utf-8 -*-
"""Alexa_reviews_AnalisisSentimientos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JqvUoy5yu0hegJgE4CdE-uoFXGWvgyn8

# ANÁLISIS DE SENTIMIENTOS

IMPORTAR BIBLIOTECAS
"""

import pandas as pd
import numpy as np
import nltk
import re
from nltk.corpus import stopwords
nltk.download('stopwords')
from nltk.stem.porter import PorterStemmer

"""IMPORTAR EL DATASET"""

df = pd.read_csv('amazon_alexa.tsv', delimiter = '\t')
df.shape

"""LIMPIEZA DE TEXTO"""

ps = PorterStemmer()
stop = stopwords.words('english')
stop.remove('didn')
stop.remove('not')
stop.remove('don')
stop.remove('wasn')
corpus = []
for i in range(0,3150):
  res = re.sub('[^a-z]',' ', df['verified_reviews'][i])
  res = res.lower()
  res = res.split()
  res = [ps.stem(pal) for pal in res if not pal in set(stop)]
  res = ' '.join(res)
  corpus.append(res)
print(corpus)

"""MODELO DE BAG OF WORDS"""

from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)

"""MATRIZ DE ATRIBUTOS X , VECTOR DE SALIDA y"""

X = X.toarray()
y = df.iloc[:,-1].values

"""UTILIZAR ALGÚN ALGORITMO DE APRENDIZAJE SUPERVISADO

DIVISIÓN DE LOS DATOS EN ENTRENAMIENTO Y PRUEBA
"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.10, random_state = 1)

"""APLICACIÓN DEL MODELO DE NAIVE BAYES"""

from sklearn.naive_bayes import MultinomialNB
clasificador = MultinomialNB(alpha = 0.1)
clasificador.fit(X_train, y_train)

"""CÁLCULO DE ACCURACY"""

y_pred = clasificador.predict(X_test)
from sklearn.metrics import accuracy_score
ACC = accuracy_score(y_test,y_pred)
print(ACC)